"""Add new columns to rooms

Revision ID: 38903a1605de
Revises: 8124befbafc9
Create Date: 2026-08-09 14:24:14.613300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38903a1605de'
down_revision: Union[str, Sequence[str], None] = '8124befbafc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('room_name', sa.Text(), server_default='Untitled Room', nullable=False))
    op.add_column('rooms', sa.Column('owner_user_id', sa.Uuid(), nullable=True))
    op.add_column('rooms', sa.Column('status', sa.Text(), server_default='waiting', nullable=False))
    op.add_column('rooms', sa.Column('is_saved', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('rooms', sa.Column('participant_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('rooms', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('ttl_expires_at', sa.DateTime(timezone=True), server_default=sa.text("now() + interval '24 hours'"), nullable=False))
    op.drop_constraint(op.f('rooms_room_code_key'), 'rooms', type_='unique')
    op.create_index('ix_rooms_owner_user_id', 'rooms', ['owner_user_id'], unique=False)
    op.create_index('ix_rooms_room_code_live', 'rooms', ['room_code'], unique=True, postgresql_where=sa.text("status IN ('waiting', 'active', 'host_grace')"))
    op.create_index('ix_rooms_ttl_expires_at', 'rooms', ['ttl_expires_at'], unique=False)
    op.create_foreign_key(None, 'rooms', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('rooms', 'name')
    op.drop_index(op.f('ix_users_username_lower'), table_name='users')
    op.create_index('ix_users_username_lower', 'users', [sa.literal_column('lower(CAST(username AS TEXT))')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username_lower', table_name='users')
    op.create_index(op.f('ix_users_username_lower'), 'users', [sa.literal_column('lower(username::text)')], unique=True)
    op.add_column('rooms', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('rooms_owner_user_id_fkey', 'rooms', type_='foreignkey')
    op.drop_index('ix_rooms_ttl_expires_at', table_name='rooms')
    op.drop_index('ix_rooms_room_code_live', table_name='rooms', postgresql_where=sa.text("status IN ('waiting', 'active', 'host_grace')"))
    op.drop_index('ix_rooms_owner_user_id', table_name='rooms')
    op.create_unique_constraint(op.f('rooms_room_code_key'), 'rooms', ['room_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('rooms', 'ttl_expires_at')
    op.drop_column('rooms', 'archived_at')
    op.drop_column('rooms', 'closed_at')
    op.drop_column('rooms', 'participant_count')
    op.drop_column('rooms', 'is_saved')
    op.drop_column('rooms', 'status')
    op.drop_column('rooms', 'owner_user_id')
    op.drop_column('rooms', 'room_name')
    # ### end Alembic commands ###
