"""add locked and host_token_hash to rooms, drop archived_at

Revision ID: 570484a25578
Revises: a6d8c16fc85f
Create Date: 2026-08-06 19:35:14.940686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570484a25578'
down_revision: Union[str, Sequence[str], None] = 'a6d8c16fc85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
