"""add index on messages room_id and sent_at

Revision ID: 6830f9a7d15c
Revises: 570484a25578
Create Date: 2026-08-08 09:05:39.613850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6830f9a7d15c'
down_revision: Union[str, Sequence[str], None] = '570484a25578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_room_id_sent_at', 'messages', ['room_id', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_room_id_sent_at', table_name='messages')
    # ### end Alembic commands ###
