"""Add users table

Revision ID: 8124befbafc9
Revises: 6830f9a7d15c
Create Date: 2026-08-09 14:09:59.205448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8124befbafc9'
down_revision: Union[str, Sequence[str], None] = '6830f9a7d15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username_lower', 'users', [sa.literal_column('lower(CAST(username AS TEXT))')], unique=True)
    op.drop_constraint(op.f('participants_role_check'), 'participants', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('participants_role_check'), 'participants', "role = ANY (ARRAY['host'::text, 'participant'::text])")
    op.drop_index('ix_users_username_lower', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
