"""add left_at to participants

Revision ID: ead128e83a76
Revises: a6d8c16fc85f
Create Date: 2026-08-01 10:31:16.572641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead128e83a76'
down_revision: Union[str, Sequence[str], None] = 'a6d8c16fc85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('left_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'left_at')
    # ### end Alembic commands ###
